# 1. 준비

In [1]:
from functools import reduce
import numpy as np
import matplotlib.pylab as plt

In [2]:
def step_func(x:np.ndarray):
    return (x>0).astype(np.int64)

In [3]:
step_func(np.arange(-3,3))

array([0, 0, 0, 0, 1, 1])

In [4]:
def sigmode(x:np.ndarray):
    return 1 / (1+np.exp(-x))

In [5]:
sigmode(np.arange(-3,3))

array([0.04742587, 0.11920292, 0.26894142, 0.5       , 0.73105858,
       0.88079708])

In [6]:
def relu(x:np.ndarray):
    return np.maximum(0,x)

In [7]:
relu(np.arange(-3,3))

array([0, 0, 0, 0, 1, 2])

In [8]:
def init_network_matrix():
    return {
        "W1" : np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
        , "b1" : np.array([0.1, 0.2, 0.3])
        , "W2" : np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
        , "b2" : np.array([0.1, 0.2])
        , "W3" : np.array([[0.1, 0.3], [0.2, 0.4]])
        , "b3" : np.array([0.1, 0.2])
    }

In [9]:
init_network_matrix()

{'W1': array([[0.1, 0.3, 0.5],
        [0.2, 0.4, 0.6]]),
 'b1': array([0.1, 0.2, 0.3]),
 'W2': array([[0.1, 0.4],
        [0.2, 0.5],
        [0.3, 0.6]]),
 'b2': array([0.1, 0.2]),
 'W3': array([[0.1, 0.3],
        [0.2, 0.4]]),
 'b3': array([0.1, 0.2])}

In [10]:
def identity_func(y):
    return y

In [11]:
identity_func(np.arange(-3,3))

array([-3, -2, -1,  0,  1,  2])

# 2. `forward`

In [12]:
def forward(network:dict, x:np.ndarray) -> np.ndarray:
    W1, W2, W3 = network["W1"], network["W2"], network["W3"]
    b1, b2, b3 = network["b1"], network["b2"], network["b3"]
    
    a1 = (x @ W1) + b1
    z1 = sigmode(a1)
    a2 = (z1 @ W2) + b2
    z2 = sigmode(a2)
    a3 = (z2 @ W3) + b3
    y = identity_func(a3)
    
    return y

In [13]:
network = init_network_matrix()

In [14]:
x = np.array([1.0, 0.5])
y = forward(network, x)
print(f"forward func:{y}")

forward func:[0.31682708 0.69627909]


# 3. `forward` revisited

In [15]:
x = np.array([1.0, 0.5])
W1 = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
b1 = np.array([0.1, 0.2, 0.3])
W2 = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
b2 = np.array([0.1, 0.2])
W3 = np.array([[0.1, 0.3], [0.2, 0.4]])
b3 = np.array([0.1, 0.2])

In [16]:
a1 = (x @ W1) + b1
z1 = sigmode(a1)
a2 = (z1 @ W2) + b2
z2 = sigmode(a2)
a3 = (z2 @ W3) + b3
y = identity_func(a3)
print(y)

[0.31682708 0.69627909]


# 3. `forward_reduce`

In [17]:
def forward_reduce(x:np.ndarray, vectors:list, bias:list, func:list) -> np.ndarray:
    
    def reduce_network_forward(x_:np.array, layer_behavior:tuple) -> np.ndarray:
        v, b, func = layer_behavior
        return func((x_@ v)+b)
    
    return list(reduce(reduce_network_forward, zip(vectors,bias,func),x))

In [18]:
network = init_network_matrix()

In [19]:
vectors = [network["W1"], network["W2"],network["W3"]]
bias = [network["b1"], network["b2"],network["b3"]]
func = [sigmode, sigmode, identity_func]

In [20]:
y2 = forward_reduce(x, vectors, bias, func)
print(f"forward_reduce func:{y2}")

forward_reduce func:[0.3168270764110298, 0.6962790898619668]


In [21]:
print(f"forward func:{y}")
print(f"forward_reduce func:{y2}")

forward func:[0.31682708 0.69627909]
forward_reduce func:[0.3168270764110298, 0.6962790898619668]
