In [17]:
import numpy as np
import pandas as pd
# def histogram_intersection(a, b):
#     v = np.minimum(a, b).sum().round(decimals=1)
#     return v
df = pd.DataFrame([(.2, .3, 1), (.0, .6, 2), (.6, .0, 3), (.2, .1, 4)],
                  columns=['dogs', 'cats','fish'])
df

dogs  cats  fish
0   0.2   0.3     1
1   0.0   0.6     2
2   0.6   0.0     3
3   0.2   0.1     4

In [20]:
np.corrcoef(df['dogs'],df['fish'])

array([[1.        , 0.30779351],
       [0.30779351, 1.        ]])

In [9]:
import numpy as np
rng = np.random.default_rng(seed=42)
xarr = rng.random((3, 3))
xarr

array([[0.77395605, 0.43887844, 0.85859792],
       [0.69736803, 0.09417735, 0.97562235],
       [0.7611397 , 0.78606431, 0.12811363]])

In [10]:
R1 = np.corrcoef(xarr)
R1

array([[ 1.        ,  0.99256089, -0.68080986],
       [ 0.99256089,  1.        , -0.76492172],
       [-0.68080986, -0.76492172,  1.        ]])